name: Ejecutar Bot Telegram

on:
  schedule:
    # Horarios UTC: 05:00 (00:00 Ec), 19:00 (14:00 Ec), 23:00 (18:00 Ec)
    - cron: '0 5,19,23 * * *'
  # Permite activarlo manualmente desde la web de GitHub si quieres probar
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # O la versión que uses

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Crear archivos de credenciales
        # GitHub Actions no guarda archivos JSON, así que los creamos al vuelo desde los Secretos
        run: |
          echo '${{ secrets.GOOGLE_TOKEN_JSON }}' > token.json
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Ejecutar el Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python cron_bot.py